### ISSUE TITLE
所以你为什么不Fork OpenWrt呢

### ISSUE THREAD

**Issue by Aloento** [hululu1068/OpenWRT-Code#3]
![image](https://github.com/hululu1068/OpenWRT-Code/assets/11802769/0f66ba22-d475-4316-948e-c8008fd2b5e3)

**Comment by TonyShizuku** [comment]
![](https://user-images.githubusercontent.com/38856864/239502888-b6bc356a-e84e-47ce-8aed-3097e988b1d2.png)
参与“物种多样性调研”中

**Comment by hululu1068** [comment]
> ![image](https://user-images.githubusercontent.com/11802769/239654882-0f66ba22-d475-4316-948e-c8008fd2b5e3.png)



> ![](https://user-images.githubusercontent.com/38856864/239502888-b6bc356a-e84e-47ce-8aed-3097e988b1d2.png) 参与“物种多样性调研”中

现在的废青、妈宝 还真不少。。。是被小日本的二次元毒害了吗

**Comment by kinosang** [comment]
![](https://user-images.githubusercontent.com/11802769/239654882-0f66ba22-d475-4316-948e-c8008fd2b5e3.png)
